baseURL: http://localhost:8080
projectName: Cookify
scenarios:
  - path: ./benchmarks/scenario1.js
    name: Consulter la section Sport
  - path: ./benchmarks/scenario2.js
    name: Consulter une recette
containers:
  - cookify-static_hosting-1
  - cookify-backend-1
